### ISSUE TITLE
System.TypeInitializationException: The type initializer for 'AspNetCore.SassCompiler.ChildProcessTracker' threw an exception.  ---> System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by solrevdev** [koenvzeijl/AspNetCore.SassCompiler#90]
When running dotent watch I got the following 

```text
[14:16:32 FTL] Host terminated unexpectedly due to an unhandled exception
System.TypeInitializationException: The type initializer for 'AspNetCore.SassCompiler.ChildProcessTracker' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'kernel32.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libkernel32.dll, 1): image not found
   at AspNetCore.SassCompiler.ChildProcessTracker.CreateJobObject(IntPtr lpJobAttributes, String name)
   at AspNetCore.SassCompiler.ChildProcessTracker..cctor()
   --- End of inner exception stack trace ---
   at AspNetCore.SassCompiler.ChildProcessTracker.AddProcess(Process process)
   at AspNetCore.SassCompiler.SassCompilerHostedService.StartProcess()
   at AspNetCore.SassCompiler.SassCompilerHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Microsoft.AspNetCore.Builder.WebApplication.Run(String url)
   at Program.<Main>$(String[] args) in /Users/solrevdev/Projects/crm.promosys/src/Web/Program.cs:line 109
[14:16:32 INF] Shut down complete
```

My csproj

```xml
<PackageReference Include="AspNetCore.SassCompiler" Version="1.52.1" />
```

My appsettings.json

```json
"SassCompiler": {
        "SourceFolder": "Styles",
        "TargetFolder": "wwwroot/css",
        "Arguments": "--style=compressed",
        "GenerateScopedCss": true,
        "ScopedCssFolders": ["Views", "Pages", "Shared", "Components"],
        // You can override specific options based on the build configuration
        "Configurations": {
            "Debug": {
                // These options apply only to Debug builds
                "Arguments": "--style=expanded"
            }
        }
    }
```

Program.cs

```cs
    var builder = WebApplication.CreateBuilder(args);

#if DEBUG
    // Setup sass compiler
    builder.Services.AddSassCompiler();
#endif

```

OS: 

OS: macOS 11.6.6 20G624 x86_64
Host: Macmini7,1

.NET
```bash
dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.6
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.300/

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6

.NET SDKs installed:
  3.1.419 [/usr/local/share/dotnet/sdk]
  6.0.300 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.25 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.25 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.5 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by sleeuwen** [comment]
Thanks for reporting this, I don't have a mac so didn't catch that before. I've created a fix that should be available shortly as version 1.52.1.1, can you try that to see if it works?

**Comment by solrevdev** [comment]
Hi @sleeuwen 

So, It seems I have the same as issue #46 

This is the workaround what prevented the compiler from restarting over and over again: 

I commented out `"ScopedCssFolders": ["Views", "Pages", "Shared", "Components"]` 

```json
"SassCompiler": {
        "SourceFolder": "Styles",
        "TargetFolder": "wwwroot/css",
        "Arguments": "--style=compressed",
        "GenerateScopedCss": true,
        //"ScopedCssFolders": ["Views", "Pages", "Shared", "Components"], // This causes the SassCompiler to keep restarting
        // You can override specific options based on the build configuration
        "Configurations": {
            "Debug": {
                // These options apply only to Debug builds
                "Arguments": "--style=expanded"
            }
        }
    }
```

Let me know if I can help in any way. 

Thanks
John

**Comment by sleeuwen** [comment]
Hi @solrevdev , thanks for figuring out what the issue was. I've implemented a fix in another PR that should fix it. The way it was currently implemented caused all the values from your appsettings to be appended to the default values, so it would contain duplicate values for those 4 folders.
